//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pc
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool E_ATX { get; set; }
        public bool Flex_ATX { get; set; }
        public bool Micro_ATX { get; set; }
        public bool Mini_DTX { get; set; }
        public bool Mini_ITX { get; set; }
        public bool SSI_CEB { get; set; }
        public bool SSI_EEB { get; set; }
        public bool Standart_ATX { get; set; }
        public bool Thin_Mini_ITX { get; set; }
        public bool Xl_ATX { get; set; }
    }
}
